
atmosphere-grid:
  number-of-layers: 100 # number of atmospheric layers
  
planet:
  planet-mass: 5.972e27 # grams
  planet-radius: 6.371e8 # cm
  number-of-zenith-angles: 4 # number of zenith angles to integrate over. 
  surface-albedo: 0.22

optical-properties:
  ir:
    k-method: RandomOverlapResortRebin
    number-of-bins: 32
    opacities:
      k-distributions: [H2O, CO2]
      CIA: [CO2-CO2, N2-N2]
      rayleigh: [H2O, CO2, N2]
      water-continuum: MT_CKD 
  solar:
    k-method: RandomOverlapResortRebin
    number-of-bins: 32
    opacities:
      k-distributions: [H2O, CO2]
      CIA: [CO2-CO2, N2-N2]
      rayleigh: [H2O, CO2, N2]
      water-continuum: MT_CKD
